# Generated by Django 3.2.17 on 2023-02-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
