# Generated by Django 4.1.5 on 2023-02-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Post', models.CharField(max_length=100, null=True)),
                ('Postion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('context', models.TextField(max_length=100000, null=True)),
            ],
        ),
    ]
