# Generated by Django 4.1.5 on 2023-02-10 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_department_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Postion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='Everyone', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mainapp.department'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule_start', models.CharField(max_length=100, null=True)),
                ('schedule_end', models.CharField(max_length=100, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100, null=True)),
                ('amount', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(choices=[('On Time', 'On Time'), ('Late', 'Late'), ('Absent', 'Absent')], max_length=100, null=True)),
                ('deduction', models.FloatField(null=True)),
                ('bonus', models.FloatField(null=True)),
                ('overttimeBonus', models.FloatField(null=True)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.salary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfQuestion', models.DateField(null=True)),
                ('checkInTime', models.DateTimeField(auto_now_add=True)),
                ('checkOutTime', models.DateTimeField(auto_now_add=True)),
                ('overtime', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
