# Generated by Django 4.1.4 on 2023-02-21 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_department_post_remove_department_postion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='context',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='department',
        ),
        migrations.RemoveField(
            model_name='leaves',
            name='title',
        ),
        migrations.AddField(
            model_name='leaves',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leaves',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='leaves',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Vacation', 'Vacation'), ('Emergency', 'Emergency')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Not Approved', 'Not Approved')], default='Pending', max_length=100),
        ),
    ]
