# Generated by Django 3.2.17 on 2023-02-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department'),
        ),
    ]
