# Generated by Django 4.1.4 on 2023-02-21 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_context_leaves_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='duration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
