# Generated by Django 3.2.17 on 2023-02-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_attendance_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkInTime',
            field=models.DateTimeField(null=True),
        ),
    ]
