# Generated by Django 3.2.17 on 2023-02-24 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Late', 'Late'), ('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10),
        ),
    ]
