# Generated by Django 3.2.17 on 2023-02-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20230224_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_start',
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkInTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkOutTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='dateOfQuestion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='Schedule_start',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_end',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
