# Generated by Django 3.2.17 on 2023-02-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20230224_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Schedule_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_end',
            field=models.TimeField(),
        ),
    ]
