# Generated by Django 3.2.17 on 2023-02-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20230224_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Schedule_start',
            new_name='schedule_start',
        ),
    ]
